name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cmk_docker_agent:$(date +%s)
    - name: Publish Docker Images to GPR
      uses: machine-learning-apps/gpr-docker-publish@v1.3
      with:
        IMAGE_NAME: cmk_docker_agent
        DOCKERFILE_PATH: 'Dockerfile'
    
